package com.udea.hb;
// Generated 14/02/2026 09:33:35 AM by Hibernate Tools 4.3.1



/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String rut;
     private String nombre;
     private String direccion;

    public Empresa() {
    }

	
    public Empresa(String rut) {
        this.rut = rut;
    }
    public Empresa(String rut, String nombre, String direccion) {
       this.rut = rut;
       this.nombre = nombre;
       this.direccion = direccion;
    }
   
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


